// packages/like-flutter-svelte/src/lib/Widget.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { parseHTML } from 'linkedom';
	import {
		type Widget,
		Alignment,
		AppRunner,
		Container,
		Text
	} from '@moonmoonbrothers/like-flutter';

	export let widget: Widget = Container({
		width: Infinity,
		height: Infinity,
		alignment: Alignment.center,
		child: Text('implement widget here')
	});

	export let ssrSize: { width: number; height: number } | undefined = undefined;
	export let width = '100%';
	export let height = '300px';

	let svgEl!: SVGSVGElement;
	let containerEl: HTMLElement;
	const { document: _document, window: _window } = parseHTML(`<svg></svg>`);
	const _svg = _document.querySelector('svg')!;
	const runner = new AppRunner({
		view: _svg,
		window: _window,
		document: _document,
		ssrSize
	});
	const innerHTML = runner.runApp(widget);
	onMount(() => {
		runner.onMount({
			view: svgEl,
			resizeTarget: containerEl
		});
	});
</script>

<div bind:this={containerEl} style="--width: {width}; --height: {height}">
	<svg bind:this={svgEl}>
		{@html innerHTML}
	</svg>
</div>

<style>
	div {
		width: var(--width);
		height: var(--height);
	}
	svg {
		width: 100%;
		height: 100%;
	}
</style>

// packages/flutterjs-solid/src/lib/Widget.tsx
import { Component, onMount } from "solid-js"
import {
  Widget as _Widget,
  AppRunner,
  Container,
  Text,
  Alignment,
} from "@moonmoonbrothers/flutterjs"

const Widget: Component<{ widget: _Widget, height?: string, width?: string  }> = ({
  width = "calc(100vw - 40px)",
  height = "calc(100vh - 40px)",
  widget = Container({
    width: Infinity,
    height: Infinity,
    alignment: Alignment.center,
    child: Text("Empty space"),
    color: "green",
  }),
}: {
  width?: string
  height?: string
  widget?: _Widget
}) => {
  let containerEl: HTMLDivElement | undefined
  let svgEl: SVGSVGElement | undefined
  onMount(() => {
    if (!containerEl) return
    if (!svgEl) return
    const runner = new AppRunner({
      view: svgEl,
    })
    runner.onMount({ resizeTarget: containerEl })
    runner.runApp(widget)
  })

  return (
    <div ref={containerEl} style={{ width, height }}>
      <svg ref={svgEl} />
    </div>
  )
}

export default Widget
