// packages/flutterjs-svelte/src/lib/Widget.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { type Widget, Alignment, AppRunner, Container, Text } from '@moonmoonbrothers/flutterjs';

	export let widget: Widget = Container({
		width: Infinity,
		height: Infinity,
		alignment: Alignment.center,
		child: Text('implement widget here')
	});

	export let ssrSize: { width: number; height: number } | undefined = undefined;
	export let width = '100%';
	export let height = '300px';

	let svgEl: SVGSVGElement;
	let containerEl: HTMLElement;
	onMount(() => {
		const runner = new AppRunner({
			view: svgEl,
			window: window,
			document: document,
			ssrSize
		});
		runner.runApp(widget);
		runner.onMount({
			resizeTarget: containerEl
		});
	});
</script>

<div bind:this={containerEl} style="--width: {width}; --height: {height}">
	<svg bind:this={svgEl} />
</div>

<style>
	div {
		width: var(--width);
		height: var(--height);
	}
	svg {
		width: 100%;
		height: 100%;
	}
</style>

// packages/flutterjs-react/src/lib/Widget.tsx
import { useEffect, useRef } from "react";
import {
  type Widget,
  Alignment,
  AppRunner,
  Container,
  Text,
} from "@moonmoonbrothers/flutterjs";

type WidgetComponentProps = {
  widget?: Widget;
  width?: string;
  height?: string;
};

function WidgetComponent({
  width = "100%",
  height = "300px",
  widget = Container({
    width: Infinity,
    height: Infinity,
    alignment: Alignment.center,
    child: Text("Hello World"),
  }),
}: WidgetComponentProps) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const svgRef = useRef<SVGSVGElement | null>(null);

  useEffect(() => {
    const runner = new AppRunner({
      view: svgRef.current!,
      window: window,
      document: document,
    });
    runner.runApp(widget);
    runner.onMount({
      resizeTarget: containerRef.current!,
    });
  }, []);

  return (
    <div style={{ width, height }} ref={containerRef}>
      <svg ref={svgRef} />
    </div>
  );
}

export default WidgetComponent;
